"""Description

Revision ID: a5f5a366314c
Revises: ad90a6fac3ce
Create Date: 2025-10-01 12:32:30.172501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f5a366314c'
down_revision: Union[str, Sequence[str], None] = 'ad90a6fac3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('meetingroom', 'decsription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('decsription', sa.TEXT(), nullable=True))
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
