"""Nullable to description

Revision ID: ad90a6fac3ce
Revises: 14732d0ca60e
Create Date: 2025-10-01 11:53:12.327327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad90a6fac3ce'
down_revision: Union[str, Sequence[str], None] = '14732d0ca60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('age', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
